// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250225145912_SeedStockData")]
    partial class SeedStockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Hapvida",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3312),
                            Industry = "Saúde",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "HAPV3"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "B3",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3352),
                            Industry = "Mercado financeiro",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "B3SA3"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Cosan",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3356),
                            Industry = "Etanol",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "CSAN3"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Lojas Renner",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3359),
                            Industry = "Vestuário",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "LREN3"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Cogna",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3363),
                            Industry = "Educação",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "COGN3"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Azevedo & Travassos",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3367),
                            Industry = "Construção",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "AZEV4"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Magazine Luiza",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3370),
                            Industry = "Varejo",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "MGLU3"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Banco Bradesco",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3374),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "BBDC4"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Ambev",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3377),
                            Industry = "Bebidas",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ABEV3"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Banco do Brasil",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3380),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "BBAS3"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Petrobras",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3383),
                            Industry = "Combustíveis",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "PETR4"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Azul",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3387),
                            Industry = "Companhias aéreas",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "AZUL4"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Itaú Unibanco",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3390),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ITUB4"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Itaúsa",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3394),
                            Industry = "Holding",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ITSA4"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "CVC",
                            CreatedAt = new DateTime(2025, 2, 25, 11, 59, 11, 887, DateTimeKind.Local).AddTicks(3397),
                            Industry = "Turismo",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "CVCB3"
                        });
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.HasOne("api.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
