// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250226150859_SeedRoleToAdminUser")]
    partial class SeedRoleToAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a0a2f394-ea8a-4bd7-a5c0-33839375e843",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "963ef919-1a70-4e5f-8d1a-74499fc5d8c3",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "68060241-8072-41c9-bef4-ab60b3f4a857",
                            RoleId = "39ee54d4-068b-4643-9e80-0f26bb65a70a"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "be1a1132-03e5-4841-9d2b-83cd68dc04a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df2b27d5-c6e0-4385-be40-1539523b9c2f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGlbNfIDoOK7DW2pYG+uw+R/cTzT1KjG9ouF0wFxIV6gA7MZl7zLATeqLsryIdjqSw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3eeaeaf2-d144-4384-a5d9-b5eb0558a751",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("api.Models.Portfolio", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("AppUserId", "StockId");

                    b.HasIndex("StockId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Hapvida",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1329),
                            Industry = "Saúde",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "HAPV3"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "B3",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1365),
                            Industry = "Mercado financeiro",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "B3SA3"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Cosan",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1369),
                            Industry = "Etanol",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "CSAN3"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Lojas Renner",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1373),
                            Industry = "Vestuário",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "LREN3"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Cogna",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1376),
                            Industry = "Educação",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "COGN3"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Azevedo & Travassos",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1381),
                            Industry = "Construção",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "AZEV4"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Magazine Luiza",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1384),
                            Industry = "Varejo",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "MGLU3"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Banco Bradesco",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1882),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "BBDC4"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Ambev",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1890),
                            Industry = "Bebidas",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ABEV3"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Banco do Brasil",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1896),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "BBAS3"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Petrobras",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1899),
                            Industry = "Combustíveis",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "PETR4"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Azul",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1902),
                            Industry = "Companhias aéreas",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "AZUL4"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Itaú Unibanco",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1905),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ITUB4"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Itaúsa",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1908),
                            Industry = "Holding",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ITSA4"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "CVC",
                            CreatedAt = new DateTime(2025, 2, 26, 12, 8, 59, 200, DateTimeKind.Local).AddTicks(1911),
                            Industry = "Turismo",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "CVCB3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.HasOne("api.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("api.Models.Portfolio", b =>
                {
                    b.HasOne("api.Models.AppUser", "AppUser")
                        .WithMany("Portfolios")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Stock", "Stock")
                        .WithMany("Portfolios")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
