// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250225180857_SeedIdentityRoleData")]
    partial class SeedIdentityRoleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1a80712a-b2ed-4a79-a7bb-fd1ba4205351",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "bfe4bdc0-ae14-4181-ae45-9f43b8adb6d0",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Hapvida",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4046),
                            Industry = "Saúde",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "HAPV3"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "B3",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4084),
                            Industry = "Mercado financeiro",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "B3SA3"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Cosan",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4088),
                            Industry = "Etanol",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "CSAN3"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Lojas Renner",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4092),
                            Industry = "Vestuário",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "LREN3"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Cogna",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4096),
                            Industry = "Educação",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "COGN3"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Azevedo & Travassos",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4104),
                            Industry = "Construção",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "AZEV4"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Magazine Luiza",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4107),
                            Industry = "Varejo",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "MGLU3"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Banco Bradesco",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4111),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "BBDC4"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Ambev",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4115),
                            Industry = "Bebidas",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ABEV3"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Banco do Brasil",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4120),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "BBAS3"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Petrobras",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4123),
                            Industry = "Combustíveis",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "PETR4"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Azul",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4127),
                            Industry = "Companhias aéreas",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "AZUL4"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Itaú Unibanco",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4130),
                            Industry = "Banco",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ITUB4"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Itaúsa",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4133),
                            Industry = "Holding",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "ITSA4"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "CVC",
                            CreatedAt = new DateTime(2025, 2, 25, 15, 8, 56, 764, DateTimeKind.Local).AddTicks(4137),
                            Industry = "Turismo",
                            LastDiv = 2m,
                            MarketCap = 3L,
                            Purchase = 1m,
                            Symbol = "CVCB3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.HasOne("api.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
